---
title: 大數據分析, 機械學習, 資料採礦 
subtitle: Big Data Analysis, Machine Learning, Data Mining
author: Jeff Lin
date: '2020-08-20'
slug: []
categories:
  - big data analysis
  - data mining
  - machine learning
  - deep learning 
  - R 
tags:
  - big data analysis
  - data mining
  - machine learning
  - deep learning
  - R  
event: null
event_url: null
location: null
address:
  street: null
  city: null
  region: null
  postcode: null
  country: null
summary: null
abstract: null
date_end: '2020-08-20T15:49:52+08:00'
all_day: no
publishDate: '2020-08-20T15:49:52+08:00'
authors: []
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
url_slides: null
url_code: null
url_pdf: null
url_video: null
slides: ''
projects: []
output: 
  html_document: 
    fig_width: 4
    fig_height: 3
    keep_md: yes
    number_sections: true

---


關於大數據分析, 機械學習, 資料採礦等所使用的資料分析方法,
在統計領域也稱為統計學習,
統計主要是討論資料分析的方法, 
因此統計學習的入們課程以討論資料分析為重心,
至於大數據資料庫的管理與存取, 不同演算法的差議,
不會在本課程討論. 另外, linear regression, logistic regression,
data visualization 在統計基礎課程已經講授.
machine learning 與 deep learning 可使用 Python, R, SAS, IBM-SPSS 等軟體.


### 大數據分析基本
* Introduction
* Descriptive Statistics
  + Missing Data
  + Rare Categories
  + Dummy Variables
  + Near-zero Variance
  + Collinearity
  + Data Transformation and Normalization
* Tidy Data  

###  Big Data Visualization
* Exploatory Data Analysis 
* R: Basic Graphics
* R: lattice package
* R: ggplot2 package
* Analytic Visualization


### Unsupervised Learning
* PCA (principal Components Analysis)
* Cluster Analysis
* Association Analysis
* Recommendation System


### Supervised Learning
* Predication: Theory and Evaluation
* Classification: Theory and Evaluation
* Linear Regression
* Logistic Regression
* R: caret package
* Penalized Regression (L1, L2, Elastic Net)
* Non-parametric Regression (GAM, LOWESS, Spline)
* Robust Regression
* Principal Component Regression (PCR)
* Partial Least Square Regression (PLSR)
* Discriminant  (LDA, QDA)
* Naive Bayes Classifier (NB)
* Regression Tree and Classification Tree (Tree)
* k-Nearest Neighbor Classification (KNN)
* Bagging
* Random Forest (RF)
* Boosting
* Support Vector Machines (SVM)

### Text Mining
* R: tidytext package
* Sentiment Analysis
* Word and Document Frequency
* Relationships Between Words
* Mining the Corpus
* Topic Modeling


### Deep Learning
* Introduction to Neural Network
* Recurrent Neural Network (RNN) and Elman Neural Networks (ENN)
* Jordan Neural Networks (JNN)
* Autoencoder
* Stacked Autoencoder and Denoising Autoencoder (DA)
* Restricted Boltzmann Machines (RBM)
* Deep Belief Networks (DBN)
* Convolutional Neural Network (CNN)
* Natural Language Processing (NLP)
