---
title: 誤差與偏差 Error and Bias
author: Jeff Lin
date: '2020-08-17'
slug: []
categories:
  - biostatistics
  - clinical trial
tags:
  - biostatistics
  - clinical trial
subtitle: ''
summary: ''
authors: []
lastmod: '2020-08-17T12:45:36+08:00'
featured: no
disable_jquery: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

{ 誤差}
({ error})
是測量值與真實值之間的差異,
誤差有 2 大類:
{ 隨機誤差}
({ random error})
與
{ 系統誤差}
({ systematic error}).


{ 隨機誤差}
({ random error})
是指抽樣所造成測量值與真實值之間的差異,
這種差異也稱抽樣誤差,
這是由於觀察到的樣本存在個體差異;
而樣本又未包含母體的全部資訊,
抽樣誤差在任何研究上是無法避免的,
隨機誤差與樣本大小有關, 樣本越大,
從樣本對母體推論的隨機誤差越小.


{ 系統誤差}
({ systematic error})
又稱為
{ 偏誤}
或
{ 偏差}
({ bias}),
測量的結果有系統性地偏離母體的真實值,
偏差影響測量結果的真實性,
通常與樣本大小無關, 不能靠統計方法解決,
偏差可來自
{ 選擇偏差}
({ selection bias}),
在確定研究個體或樣本時,
進入研究的個體與未進入研究的個體,
在某些特徵上存在差異,
如選擇研究個體的偏差而造成測量結果的的偏差,
如倖存者偏差,
由於調查死亡病例很困難,
只能調查其倖存者, 由此不能全面反映該疾病的狀況.
另一常見因調查方法或調查內容不恰當,
受訪者不願意接受,
由於無回答者往往可能不同於一般受訪者,
造成所謂無回答偏差.



偏差可來自
{ 資訊偏差}
({ information bias}),
常見為
{ 回憶偏差}
({ recall bias})
和
{ 報告偏差}
({ reporting bias}),
由於個體某些特徵不同,
造成對一些問題的回答不準確而引起偏差.
例如病例組因曾患過某特定疾病,
而能夠回憶起過去的暴露危險因子,
而對照組則常遺忘過去的情況.
在調查某些敏感性問題時,
受訪者可能不願真實回答而造成報告偏差.


偏差也可來自外在因素的干擾, 如
{ 干擾偏差}
({ confounding bias}),
{ 干擾因子}
({ confounding factor},
{ confounder})
是指特定共變數同時影響危險因子與反應變數,
研究危險因子與反應變數的因果關係時,
干擾因子與危險因子與反應變數有一定的關聯,
由於干擾因子, 影響了危險因子與反應變數關聯強度或因果判斷.

統計方法中無論研究設計或資料分析是將隨機誤差假設成為一機率分配,
儘量控制系統誤差, 資訊偏差 與 干擾偏差,
若無法控制系統誤差,
也必須研究系統誤差是否有一致的方向性,
例如結論偏向某一方向,
系統誤差若有一致的偏向,
則統計必須嘗試估計此一致的偏向的大小,
修正結論的正確性,
統計方法中是無法處理無特定偏向的系統誤差,
研究者在執行研究時必須隨時控制可能的系統誤差,
資訊偏差 與 干擾偏差.

